---
spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
    applicarion:
      name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: htttp://eureka-dev.com:7001/eureka/

---
server:
  port: 8202
spring:
  profiles: test
    applicarion:
      name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: htttp://eureka-test.com:7001/eureka/